name: newsflash 
base: core24
version: '5.0.0-beta2'
adopt-info: newsflash
compression: lzo
issues: https://github.com/soumyaDghosh/newsflash-snap/issues
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
  armhf:

layout:
  /usr/lib/x86_64-linux-gnu/webkitgtk-6.0:
    symlink: $SNAP/webkitgtk-platform/usr/lib/x86_64-linux-gnu/webkitgtk-6.0

slots:
  newsflash:
    interface: dbus
    bus: session
    name: io.gitlab.news_flash.NewsFlash

parts:
  rustup:
    plugin: rust
    source: .
    override-build: ""
    override-prime: ""

  clapper:
    plugin: meson
    source: https://github.com/Rafostar/clapper.git
    source-tag: '0.6.0'
    source-depth: 1
    build-snaps:
      - ffmpeg-2404-sdk
      - blueprint-compiler
    build-environment:
      - PKG_CONFIG_PATH: /snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:$PKG_CONFIG_PATH
      - PATH: ${CRAFT_STAGE}/usr/bin:${PATH}
    meson-parameters:
      - --prefix=/usr
      - -Dclapper=enabled
      - -Dclapper-gtk=enabled
      - -Dclapper-app=disabled
      - -Dintrospection=enabled
      - -Dvapi=enabled
    build-packages:
      - libgstreamer-plugins-base1.0-dev
      - libgudev-1.0-dev
      - libsass-dev
      - sassc
      - libdv4-dev
      - libdvdread-dev
      - libdvdnav-dev
      - libass-dev
      - libuchardet-dev
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig

  newsflash:
    after: [rustup, clapper]
    plugin: meson
    source: https://gitlab.com/api/v4/projects/8320003/packages/generic/newsflash/${SNAPCRAFT_PROJECT_VERSION}/newsflash-${SNAPCRAFT_PROJECT_VERSION}.tar.xz
    build-environment:
      - CARGO_BUILD_JOBS: ${CRAFT_PARALLEL_BUILD_COUNT}
      - PKG_CONFIG_PATH: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pkgconfig:/snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:${PKG_CONFIG_PATH}
      - GI_TYPELIB_PATH: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/girepository-1.0:${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/girepository-1.0:${GI_TYPELIB_PATH}
      - LD_LIBRARY_PATH: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:${LD_LIBRARY_PATH}
      - PATH: ${HOME}/.cargo/bin:${PATH}
    meson-parameters:
      - --prefix=/snap/newsflash/current/usr
      - -Dbuildtype=release
      - -Doptimization=3
    build-packages:
      - libclang-20-dev
      - libssl-dev
      - libgstreamer1.0-dev
    build-snaps:
      - webkitgtk-6-gnome-2404-sdk
    organize:
      snap/newsflash/current: .
    parse-info: [ usr/share/metainfo/io.gitlab.news_flash.NewsFlash.appdata.xml ]

plugs:
  webkitgtk-6-gnome-2404:
    interface: content
    target: $SNAP/webkitgtk-platform
    default-provider: webkitgtk-6-gnome-2404

  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404

apps:
  newsflash:
    command: usr/bin/io.gitlab.news_flash.NewsFlash
    extensions: [gnome]
    common-id: io.gitlab.news_flash.NewsFlash
    desktop: usr/share/applications/io.gitlab.news_flash.NewsFlash.desktop
    environment:
      LD_LIBRARY_PATH: "$SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:\
                       $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:\
                       $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkitgtk-6.0:\
                       $LD_LIBRARY_PATH"
    plugs:
      - unity7
      - network
      - network-status
      - network-observe
      - system-observe
