name: newsflash 
base: core22
adopt-info: newsflash
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

license: GPL-3.0
compression: lzo
source-code: https://gitlab.com/news_flash/news_flash_gtk.git
issues: https://github.com/soumyaDghosh/newsflash-snap/issues
grade: stable
confinement: strict 

layout:
  /usr/lib/x86_64-linux-gnu/webkitgtk-6.0:
    bind: $SNAP/webkitgtk-platform/usr/lib/x86_64-linux-gnu/webkitgtk-6.0

slots:
  newsflash:
    interface: dbus
    bus: session
    name: io.gitlab.news_flash.NewsFlash

parts:
  blueprint-compiler:
    source: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
    source-tag: 'v0.10.0'
# ext:updatesnap
#   version-format:
#     ignore: true
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-prime: ''

  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'

  newsflash:
    after: [rustup, blueprint-compiler]
    plugin: meson
    source: https://gitlab.com/news-flash/news_flash_gtk.git
    source-tag: 'v.3.1.1'
#ext:updatesnap
#  version-format:
#    format: 'v.%M.%m.%R'
    source-depth: 1
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PKG_CONFIG_PATH: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:$PKG_CONFIG_PATH
      - PATH: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/bin:$PATH
      - PYTHONPATH: ${CRAFT_STAGE}/usr/lib/python3/dist-packages:$PYTHONPATH
      - GI_TYPELIB_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:/snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0
      - XDG_DATA_DIRS: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/share:$XDG_DATA_DIRS
      - LD_LIBRARY_PATH: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/webkitgtk-6.0:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$LD_LIBRARY_PATH
    meson-parameters:
      - --prefix=/snap/newsflash/current/usr
      - -Dbuildtype=release
      - -Doptimization=2
    build-packages:
      - libssl-dev
      - libelf1
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/newsflash.patch
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/newsflash/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    build-snaps:
      - webkitgtk-6-gnome-2204-sdk/latest/stable
    organize:
      snap/newsflash/current: .
    parse-info: [ usr/share/metainfo/io.gitlab.news_flash.NewsFlash.appdata.xml ]

plugs:
  webkitgtk-6-gnome-2204:
    interface: content
    target: $SNAP/webkitgtk-platform
    default-provider: webkitgtk-6-gnome-2204

apps:
  newsflash:
    command: usr/bin/io.gitlab.news_flash.NewsFlash
    extensions: [gnome]
    common-id: io.gitlab.news_flash.NewsFlash
    desktop: usr/share/applications/io.gitlab.news_flash.NewsFlash.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/webkitgtk-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/webkitgtk-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkitgtk-6.0:$LD_LIBRARY_PATH
      GDK_DEBUG: 'portals'
    plugs:
      - unity7
      - network
      - network-status
