name: newsflash 
base: core24
version: '3.3.2'
adopt-info: newsflash
compression: lzo
issues: https://github.com/soumyaDghosh/newsflash-snap/issues
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
  armhf:

layout:
  /usr/lib/x86_64-linux-gnu/webkitgtk-6.0:
    bind: $SNAP/webkitgtk-platform/usr/lib/x86_64-linux-gnu/webkitgtk-6.0

slots:
  newsflash:
    interface: dbus
    bus: session
    name: io.gitlab.news_flash.NewsFlash

parts:
  blueprint-compiler:
    source: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
    source-tag: 'v0.12.0'
# ext:updatesnap
#   version-format:
#     ignore: true
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-prime: ''

  rustup:
    plugin: rust
    source: .
    rust-channel: "1.78"
    override-build: ""
    override-prime: ""

  clapper:
    plugin: meson
    source: https://github.com/Rafostar/clapper.git
    source-tag: '0.6.0'
    source-depth: 1
    build-snaps:
      - ffmpeg-2404-sdk/latest/candidate
      - ffmpeg-2404/latest/candidate
    build-environment:
      - PKG_CONFIG_PATH: /snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:$PKG_CONFIG_PATH
      - PATH: ${CRAFT_STAGE}/usr/bin:${PATH}
    meson-parameters:
      - --prefix=/usr
      - -Dclapper=enabled
      - -Dclapper-gtk=enabled
      - -Dclapper-app=disabled
      - -Dintrospection=enabled
      - -Dvapi=enabled
    build-packages:
      - libgstreamer-plugins-base1.0-dev
      - libgudev-1.0-dev
      - libsass-dev
      - sassc
      - libdv4-dev
      - libdvdread-dev
      - libdvdnav-dev
      - libass-dev
      - libuchardet-dev
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig

  newsflash:
    after: [rustup, blueprint-compiler, clapper]
    plugin: meson
    source: https://gitlab.com/api/v4/projects/8320003/packages/generic/newsflash/${SNAPCRAFT_PROJECT_VERSION}/newsflash-${SNAPCRAFT_PROJECT_VERSION}.tar.xz
    build-environment:
      - CARGO_BUILD_JOBS: ${CRAFT_PARALLEL_BUILD_COUNT}
      - PKG_CONFIG_PATH: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pkgconfig:${PKG_CONFIG_PATH}
      - PATH: ${HOME}/.cargo/bin:/snap/webkitgtk-6-gnome-2404-sdk/current/usr/bin:${PATH}
      - PYTHONPATH: ${CRAFT_STAGE}/usr/lib/python3/dist-packages:${PYTHONPATH}
      - GI_TYPELIB_PATH: /snap/gnome-46-2404-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/girepository-1.0:/snap/gnome-46-2404-sdk/current/usr/lib/girepository-1.0:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0:$GI_TYPELIB_PATH
      - XDG_DATA_DIRS: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/share:$XDG_DATA_DIRS
      - LD_LIBRARY_PATH: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib:/snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/webkitgtk-6.0:/snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/girepository-1.0:${LD_LIBRARY_PATH}
    meson-parameters:
      - --prefix=/snap/newsflash/current/usr
      - -Dbuildtype=release
      - -Doptimization=2
    build-packages:
      - libssl-dev
      - libelf1
      - libgstreamer1.0-dev
    stage-packages:
      - libicu74
      - libavif16
    override-pull: |
      craftctl default
      patch -p1 < ${CRAFT_PROJECT_DIR}/newsflash.patch
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/newsflash/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    build-snaps:
      - webkitgtk-6-gnome-2404-sdk/latest/candidate
      - webkitgtk-6-gnome-2404/latest/candidate
    organize:
      snap/newsflash/current: .
    parse-info: [ usr/share/metainfo/io.gitlab.news_flash.NewsFlash.appdata.xml ]

plugs:
  webkitgtk-6-gnome-2404:
    interface: content
    target: $SNAP/webkitgtk-platform
    default-provider: webkitgtk-6-gnome-2404

  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404

apps:
  newsflash:
    command: usr/bin/io.gitlab.news_flash.NewsFlash
    extensions: [gnome]
    common-id: io.gitlab.news_flash.NewsFlash
    desktop: usr/share/applications/io.gitlab.news_flash.NewsFlash.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkitgtk-6.0:$LD_LIBRARY_PATH
    plugs:
      - unity7
      - network
      - network-status
      - system-observe
