name: newsflash # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: newsflash
architectures:
  - build-on: amd64
license: GPL-3.0
compression: lzo
source-code: https://gitlab.com/news-flash/news_flash_gtk
issues: https://github.com/soumyaDghosh/newsflash-snap/issues
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

package-repositories:
  - type: apt
    components: [main, multiverse, restricted, universe]
    suites: [kinetic, kinetic-backports, kinetic-security, kinetic-updates]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://security.ubuntu.com/ubuntu
parts:
  webkitgtk:
    source: https://webkitgtk.org/releases/webkitgtk-2.40.1.tar.xz
    plugin: cmake
    build-environment:
      - PYTHONPATH: "$PYTHONPATH:$CRAFT_STAGE/usr/lib"
    cmake-parameters:
      - -DPORT=GTK
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_LIBDIR=lib
      - -DCMAKE_INSTALL_LIBEXECDIR=lib
      - -DCMAKE_SKIP_RPATH=ON
      - -DUSE_AVIF=ON
      - -DUSE_GTK4=ON
      - -DENABLE_DOCUMENTATION=ON
      - -DENABLE_MINIBROWSER=ON
    build-packages:
      - ruby-all-dev
      - libfreetype-dev
      - libgcrypt20-dev
      - libicu-dev
      - libjpeg-dev
      - unifdef
      - libmanette-0.2-dev
      - libjpeg-dev
      - libpng-dev
      - libxslt1-dev
      - libsqlite3-dev
      - libcurl4-gnutls-dev
      - libenchant-2-dev
      - libsoup2.4-dev
      - gi-docgen
    stage-packages:
      - gi-docgen
  rustup:
    after: [webkitgtk]
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  newsflash:
    after: [rustup, webkitgtk]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.com/news-flash/news_flash_gtk.git
    source-tag: v.2.2.4
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    meson-parameters:
      - --prefix=/snap/newsflash/current/usr
    build-packages:
      - libssl-dev
    organize:
      snap/newsflash/current/usr: usr
    parse-info: [usr/share/metainfo/com.gitlab.newsflash.appdata.xml]
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - newsflash
      - rustup
      - webkitgtk
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gnome-42-2204
      - gtk-common-themes
      - core22
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "gtk-common-themes" "core22"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
apps:
  newsflash:
    command: usr/bin/com.gitlab.newsflash
    extensions: [gnome]
    common-id: com.gitlab.newsflash
    desktop: usr/share/applications/com.gitlab.newsflash.desktop
