name: Deploy Newsflash
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
permissions:
  id-token: write
  contents: read
jobs:
  deploy-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Build Newsflash Snap
        uses: snapcore/action-build@v1
        id: snapcraft-build
        with:
          snapcraft-args: "-v"
      - uses: actions/upload-artifact@v3
        with:
          name: newsflash-snap
          path: ${{ steps.snapcraft-build.outputs.snap }}
#      - name: Upload and release tube-converter Snap
#        uses: snapcore/action-publish@v1
#        env: 
#          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
#       with:
#          snap: ${{ steps.snapcraft-build.outputs.snap }}
#          release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}
#
